name: Publish
on:
  release:
    types: [published]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Add Apple developer ID certificate
        env: 
          MACOS_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}
        run: |
          echo $MACOS_CERTIFICATE > certificate.base64
          base64 -i certificate.base64 --decode > certificate.p12
          security create-keychain -p TMP_KEYCHAIN_PASS build.keychain 
          security default-keychain -s build.keychain
          security unlock-keychain -p TMP_KEYCHAIN_PASS build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k TMP_KEYCHAIN_PASS build.keychain
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electron app
        run: npm install && npm run make
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with:
          name: api-video.dmg
          path: out/make/api-video.dmg
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electron app
        run: npm install && npm run make 

      - uses: actions/upload-artifact@v2
        with:
          name: api-video-win32-x64-setup.exe
          path: out/make/squirrel.windows/x64/api-video-win32-x64-setup.exe
  release:
    name: Upload Release Asset
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: api-video.dmg
      - uses: actions/download-artifact@v2
        with:
          name: api-video-win32-x64-setup.exe
      - name: ls
        run: ls
      - name: Upload macos binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./api-video.dmg
          asset_name: api-video-${{ github.ref_name }}-darwin-x64.dmg
          tag: ${{ github.ref }}
          overwrite: true    
      - name: Upload windows binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./api-video-win32-x64-setup.exe
          asset_name: api-video-${{ github.ref_name }}-win32-x64-setup.exe
          tag: ${{ github.ref }}
          overwrite: true